### ISSUE TITLE
Microcalcification detection using CNN !

### ISSUE THREAD

**Issue by Maya1994** [ecobost/cnn4brca#2]
hello, Thanks for this code, 
Actually, I'm interested in microcalcification detection using CNN algorithm. 
Is it possible to modify your code so that i detect microcalcif in mammo ? if yes, How can i proceed plz !

Thanks,

**Comment by ecobost** [comment]
The approach is the same for any kind of lesion segmentation. Lesion segmentation meaning given a mammogram as input output an image of the same dimensions with 1s where the lesion is present and 0 everywhere else (or equivalently output an image of the same size with per-pixel probabilities of presence of lesion). The difference is that the mask used for training have to mark microcalcifications as positive and the rest as negative, (whether to mark both masses and microcalcifications as positive is a design decision). Once you've gotten a microcalcification database and generated the masks, you should be able to use code like this without change. In theory if you want to segment cats from no cats and have a database with cats mask, this still could be useful

**Comment by Maya1994** [comment]
thanks for ur answer ;)
