### ISSUE TITLE
 createMasks.m

### ISSUE THREAD

**Issue by EngNala** [ecobost/cnn4brca#5]
Hello, 
how can i use  createMasks.m for my own single mammogram please ? 
I didnt understand the code !! should I run it with matlab only , is there any python version ?
Sorry if my question sound stupid !!! 

Many Thanks,

**Comment by ecobost** [comment]
Hi Eng, 
That particular part does works in Octave/Matlab, I developed it in Octave which is Matlab-like but freely available online so maybe you can download it and then run createMask on it. However, I don't know whether is useful in your case, what createMask.m does is take an outline (a series of x,y coordinates) and creates the contour of the lesion from it, if you do not have the outlines in the format they were provided in BCDR then I don't know if it will be that useful, if you are looking to do iimage segmentation in a single image, maybe you should look into some of the python image processing modules like [scikit-image](http://scikit-image.org/docs/dev/auto_examples/#segmentation-of-objects) or [scipy](http://www.scipy-lectures.org/advanced/image_processing/)
