### ISSUE TITLE
error while running ./train.py

### ISSUE THREAD

**Issue by mohamed945** [ecobost/cnn4brca#6]
hello, 
I'm trying to test your code,
but i come with this error, 

Traceback (most recent call last):
  File "train.py", line 174, in <module>
    train()
  File "train.py", line 148, in train
    loss_summary = tf.summary.scalar(['logistic_loss', 'loss'], [train_logistic_loss, train_loss], collections=[])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/summary/summary.py", line 118, in scalar
    name = _clean_tag(name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/summary/summary.py", line 90, in _clean_tag
    new_name = _INVALID_TAG_CHARACTERS.sub('_', name)
TypeError: expected string or bytes-like object

Thanks,

**Comment by ecobost** [comment]
That line looks like it should be:
loss_summary = tf.summary.scalar(['logistic_loss', 'loss'],
[train_logistic_loss, train_loss], collections=[])

**Comment by mohamed945** [comment]
thank you for the answer

**Comment by ecobost** [comment]
In tf 1.0,m [summary.scalar] (https://www.tensorflow.org/api_docs/python/tf/summary/scalar), receives only one argument, you would have to modify the code to have each summary sent separately, I bet the new way scalar summaries is managed is different so I would read their docs first. Or you could comment that line entirely out but hen tensorboard won't log the training loss.
